# Site
title:              Manoel V. Machado
bio:                "Computer Engineer, Machine Learning Engineer professional and occasional musician."
description:        "That place is where I talk about my projects and my life."
reading_time:       true
words_per_minute:   100
logo:               'assets/img/avatar.jpg'
background:         'assets/img/placeholder-big.webp'
locale:             pt_BR
url:                https://lerax.me

# Jekyll
permalink:          /:categories/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Google Analytics
google_analytics: G-GMZWEDNP1F

# Comments
disqus_shortname:   ryukinix

# Social
# if you don't have any of social below, comment the line.
#bing-verify:
email:              manoel_vilela@engineer.com
#facebook:
github:             ryukinix
stackoverflow:      3749971/lerax
linkedin:           lerax
quora:              Manoel-Vilela
twitter:            ryukinix
steam:              ryukinix
#xing:              username
instagram:          manoelnt0
keybase:            lerax
custom:             server.manoel.dev
#lastfm:             username
#tumblr:             username
#pinterest:         username
#foursquare:        username
#dribbble:          username
youtube:            ManoelVilelaNeto
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username

defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true


# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com


feed:
  posts_limit: 50

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js,
          package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
include: [.well-known]
